### ISSUE TITLE
The nova-network wasn't started.

### ISSUE THREAD

**Issue by guanxiaohua2k6** [nii-cloud/dodai-deploy#3]
After I installed nova, I confirmed the status of service nova-network with the following command, and found nova-network wasn't started.

```
$ status nova-network
nova-network stop/waiting
```

BTW, there are error messages in /etc/nova/nova-network.

2011-11-07 10:44:37,499 CRITICAL nova [-] Unexpected error while running command.
Command: sudo iptables-save -t filter
Exit code: 1
Stdout: ''
Stderr: 'sudo: iptables-save: command not found\n'
(nova): TRACE: Traceback (most recent call last):
(nova): TRACE:   File "/usr/bin/nova-network", line 49, in <module>
(nova): TRACE:     service.wait()
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/nova/service.py", line 357, in wait
(nova): TRACE:     _launcher.wait()
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/nova/service.py", line 107, in wait
(nova): TRACE:     service.wait()
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/eventlet/greenthread.py", line 166, in wait
(nova): TRACE:     return self._exit_event.wait()
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/eventlet/event.py", line 116, in wait
(nova): TRACE:     return hubs.get_hub().switch()
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 177, in switch
(nova): TRACE:     return self.greenlet.switch()
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/eventlet/greenthread.py", line 192, in main
(nova): TRACE:     result = function(_args, *_kwargs)
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/nova/service.py", line 77, in run_server
(nova): TRACE:     server.start()
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/nova/service.py", line 137, in start
(nova): TRACE:     self.manager.init_host()
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/nova/network/manager.py", line 1002, in init_host
(nova): TRACE:     self.driver.init_host()
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/nova/network/linux_net.py", line 404, in init_host
(nova): TRACE:     iptables_manager.apply()
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/nova/utils.py", line 685, in inner
(nova): TRACE:     retval = f(_args, *_kwargs)
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/nova/network/linux_net.py", line 312, in apply
(nova): TRACE:     attempts=5)
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/nova/network/linux_net.py", line 735, in _execute
(nova): TRACE:     return utils.execute(_cmd, *_kwargs)
(nova): TRACE:   File "/usr/lib/python2.7/dist-packages/nova/utils.py", line 188, in execute
(nova): TRACE:     cmd=' '.join(cmd))
(nova): TRACE: ProcessExecutionError: Unexpected error while running command.
(nova): TRACE: Command: sudo iptables-save -t filter
(nova): TRACE: Exit code: 1
(nova): TRACE: Stdout: ''
(nova): TRACE: Stderr: 'sudo: iptables-save: command not found\n'

**Comment by guanxiaohua2k6** [comment]
The reason is that package iptables wasn't installed when installing nova-network.

The issue is fixed in the following commit.
https://github.com/nii-cloud/dodai-deploy/commit/12330f1a8c9435658c4850f18df9bd654d78444f
https://github.com/nii-cloud/dodai-deploy/commit/ccb675e71433fe1f70a2decc796098bb843cb99a
