### ISSUE TITLE
Glance installation failed due to "ImportError: No module named httplib2"

### ISSUE THREAD

**Issue by guanxiaohua2k6** [nii-cloud/dodai-deploy#7]
When I installed glance, the following error occurred.

Traceback (most recent call last):
File "/usr/bin/glance-manage", line 47, in <module>
import glance.registry.db
File "/usr/lib/python2.7/dist-packages/glance/registry/**init**.py", line 24, in <module>
from glance.registry import client
File "/usr/lib/python2.7/dist-packages/glance/registry/client.py", line 26, in <module>
from glance.common.client import BaseClient
File "/usr/lib/python2.7/dist-packages/glance/common/client.py", line 13, in <module>
from glance.common import auth
File "/usr/lib/python2.7/dist-packages/glance/common/auth.py", line 33, in <module>
import httplib2
ImportError: No module named httplib2

**Comment by guanxiaohua2k6** [comment]
Because the order to install glance and python-httplib2 is not determined in puppet manifests, it is possible to install glance firstly, then the error occurred. The bug is fixed in the following commit.

https://github.com/nii-cloud/dodai-deploy/commit/ec8917a7d873f0a46c4fc448bfa34c3dee904641
